name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: 18
        registry-url: https://registry.npmjs.org/
    - name: Install dependencies
      run: pnpm install
    - name: Build sources
      run: pnpm build
    - name: Package outputs
      run: zip freeflight-interpark.zip ./dist -r
    - name: Upload to Release
      uses: csexton/release-asset-action@v2
      with:
        pattern: freeflight-interpark.zip
        github-token: ${{secrets.GITHUB_TOKEN}}
        release-url: ${{github.event.release.upload_url}}
